### PR TITLE
Add an option to use raw mode, allows for much larger data captures

### PR DESCRIPTION
**Pull request by MasterJubei**
Hey, thanks for making this. It would be great if we could use the raw option mode on the scope so we can gather much larger amounts of samples. 1000 is too limiting in my case, raw mode lets you use up to the scope's memory depth.

### CODE REVIEW

**Comment by tspspi** [comment]
Wow sounds like a very cool idea - if I see this correctly the suggested changes currently only set a different mode but have not added parsing capabilities if I'm correct? So currently the querying of raw data would not work with the suggested changes? (I could add those over the course of the next few days for sure but won't make much sense in case you already have a working implementation)

**Comment by MasterJubei** [comment]
Sorry, could you clarify a bit on the parsing capabilities? I probably just didn't look at all the functions, but all the functions I tried seem to work still after doing this. Everything should still be in ASCII
The returned waveform data is still the same type of data, I can graph it as is.

Here's what I was trying to do, just get some FFTs. It's  not a minimal example, but at least shows the data returned is workable right away.
My import is probably going to be different since I copied the folder locally
The same code works if I have it in raw mode vs normal mode

```python
from pymso5000.src.pymso5000 import MSO5000
import numpy as np
import matplotlib.pyplot as plt
from scipy.fftpack import fft
from scipy.signal import find_peaks


with MSO5000(
      address = "192.168.1.170",
      rawMode = True,
   ) as mso:
   print(f"Identify: {mso.identify()}")

   # Set enabled channels
   mso.set_channel_enable(0, True)  
   mso.set_channel_enable(1, False)
   mso.set_channel_enable(2, False) 
   mso.set_channel_enable(3, False)

   data = mso.query_waveform((0,0)) 
   print(mso._get_num_points())

   # plt.plot(data['x'], data['y0'], label = "Ch1")
   # plt.plot(data['x'], data['y1'], label = "Ch2")
   
   # Verify number of sample points
   N = len(data['y0'])
   print(f"Number of sample points: {N}")

   T = data['x'][1] - data['x'][0] # sample spacing in seconds
   print (T*10**9)

   # Convert the data to numpy arrays.
   x = np.asarray(data['x']) # Seconds
   y = np.asarray(data['y0']) # Volts

   yf = fft(y)
   xf = np.linspace(0.0, 1.0/(2.0*T), N//2)

   # Make sure our sample rate is correct...
   print(f"Sample rate: {(data['x'][1] - data['x'][0])*10**9} ns")

   # dBV Plot
   fig, ax = plt.subplots()
   ax.plot(xf/10**6, 20*np.log10(2.0/N * np.abs(yf[:N//2])))
   ax.set_xlabel('Frequency (MHz)')
   ax.set_ylabel('Amplitude (dBV)')
   ax.set_title('FFT of AD9717 Output')

   # Find the peaks and label them, they can't be too close to eachother
   peaks, _ = find_peaks(2.0/N * np.abs(yf[:N//2]), height=0.001, distance=100)

   print(f"There are {len(peaks)} peaks in the FFT")

   # Label all peaks greater than -70 dBV
   for i in range(len(peaks)):
      if 20*np.log10(2.0/N * np.abs(yf[peaks][i])) > -70:
         ax.annotate(str(round(xf[peaks][i]/(10**6), 10)) + ' MHz', (xf[peaks][i]/10**6, 20*np.log10(2.0/N * np.abs(yf[peaks][i]))))

   plt.xlim(0, 100)
   plt.show()

```

**Comment by tspspi** [comment]
Oh sorry I did not look into the change in detail - just looked up in the manual. I thought it would change also the data format transmitted but since it doesn't everything should work out. The manual states the oscilloscope has to be in Stop mode for this query to be allowed? Should we add a check to the query function to ensure this is satisfied? (Going to merge your changes after testing latest Friday for sure).

**Comment by MasterJubei** [comment]
Yeah that is a good idea, I went ahead and tried to run it while it wasn't paused and it simply returns 0 points back. I'll see if I can throw in a check for that.

**Comment by MasterJubei** [comment]
I went ahead and added a check for stop mode. I also made the scope identification check only for "MSO5" instead of "MSO50" as before it wouldn't work on the MSO5104.

**Comment by tspspi** [comment]
Sorry for the late merge - I've now merged all the commits after rudimentary testing into the current master branch

**Comment by MasterJubei** [comment]
Awesome, thanks!

**Pull request merged**
